### ISSUE TITLE
[Question] setOptions vs setParams

### ISSUE THREAD

**Issue by shahankit** [satya164/react-navigation-addons#12]
`react-navigation` by default provides setParams in `this.props.navigation`. What is the difference between setParams and setOptions?

**Comment by GollyJer** [comment]
`setParams` starts as an empty object and allows you to pass whatever you want into it.
`setOptions` makes it possible to set .[navigationOptions](https://reactnavigation.org/docs/navigators/stack#Screen-Navigation-Options) at the screen level AND use the local component props... normally not possible.
