### ISSUE TITLE
this.props.navigation.addListener is not a function

### ISSUE THREAD

**Issue by kaiyes** [satya164/react-navigation-addons#21]
![simulator screen shot - iphone 6 - 2017-09-30 at 10 43 26](https://user-images.githubusercontent.com/5293742/31042528-37b38638-a5cc-11e7-9aec-c254ec744821.png)

**Comment by kaiyes** [comment]
"react-native": "0.47.1",
not using expo. Package installed fine using `yarn add satya164/react-navigation-addons` . Importing enhance properly as well. Using `this.props.navigations.addListener('focus',  _this.handleWhatever)` causes this red screen of error. 🗡  🈂️ 🉑

**Comment by elliottjro** [comment]
@kaiyes this means you didnt wrap your stack/tab navigators in `enhance()`

**Comment by kaiyes** [comment]
@ElliottJRo  thanks. Solved this issue by abandoning this approach and using a hack. passing a new Date() object in `componentWillReceieveProps` makes the component re render everytime it is rendered. Hope react navigation solves this issue soon. Until that time, this hack will do. See #51 in react navigation issues
