### ISSUE TITLE
Unable to resolve module `react/lib/ReactComponentWithPureRenderMixin`

### ISSUE THREAD

**Issue by joncursi** [satya164/react-navigation-addons#5]
Error line: https://github.com/satya164/react-navigation-addons/blob/master/src/enhanceScreen.js#L4

See also: https://github.com/react-community/react-navigation/issues/923

**Comment by satya164** [comment]
It's removed in latest React. We need to replace it with https://www.npmjs.com/package/react-addons-shallow-compare

**Comment by satya164** [comment]
PR welcome!
